src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NewsRepository::class)]
class News
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $contentobject_id = null;

    #[ORM\Column(nullable: true)]
    private ?int $creator_id = null;

    #[ORM\Column(length: 255)]
    private ?string $publication_date = null;

    #[ORM\Column(length: 255)]
    private ?string $url_path = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $author_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $author_email = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publish_date = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $tags = null;

    #[ORM\Column(nullable: true)]
    private ?int $related_band = null;

    #[ORM\Column(nullable: true)]
    private ?int $related_album = null;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $related_news = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?int $comments_count = 0;

    #[ORM\Column(type: "text", nullable: true)]
    private ?string $image_reference = null;

    #[ORM\Column(length: 255)]
    private ?string $related_content = null;

    #[ORM\Column]
    private ?int $views = 0;

    #[ORM\Column]
    private ?int $is_redesign_version = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $intro = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $optional_tag = null;

    #[ORM\Column(length: 255)]
    private ?string $img_main = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $slider = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $public = null;

    #[ORM\Column(length: 255)]
    private ?string $added = null;

    public function incrementViews()
    {
        $this->views++;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContentobjectId(): ?string
    {
        return $this->contentobject_id;
    }

    public function setContentobjectId(string $contentobject_id): static
    {
        $this->contentobject_id = $contentobject_id;

        return $this;
    }

    public function getCreatorId(): ?int
    {
        return $this->creator_id;
    }

    public function setCreatorId(int $creator_id): static
    {
        $this->creator_id = $creator_id;

        return $this;
    }

    public function getPublicationDate(): ?string
    {
        return $this->publication_date;
    }

    public function setPublicationDate(string $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getUrlPath(): ?string
    {
        return $this->url_path;
    }

    public function setUrlPath(string $url_path): static
    {
        $this->url_path = $url_path;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthorName(): ?string
    {
        return $this->author_name;
    }

    public function setAuthorName(string $author_name): static
    {
        $this->author_name = $author_name;

        return $this;
    }

    public function getAuthorEmail(): ?string
    {
        return $this->author_email;
    }

    public function setAuthorEmail(string $author_email): static
    {
        $this->author_email = $author_email;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): static
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): static
    {
        $this->tags = $tags;

        return $this;
    }

    public function getRelatedBand(): ?int
    {
        return $this->related_band;
    }

    public function setRelatedBand(?int $related_band): static
    {
        $this->related_band = $related_band;

        return $this;
    }

    public function getRelatedAlbum(): ?int
    {
        return $this->related_album;
    }

    public function setRelatedAlbum(?int $related_album): static
    {
        $this->related_album = $related_album;

        return $this;
    }

    public function getRelatedNews(): ?string
    {
        return $this->related_news;
    }

    public function setRelatedNews(?string $related_news): static
    {
        $this->related_news = $related_news;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCommentsCount(): ?int
    {
        return $this->comments_count;
    }

    public function setCommentsCount(int $comments_count): static
    {
        $this->comments_count = $comments_count;

        return $this;
    }

    public function getImageReference(): ?string
    {
        return $this->image_reference;
    }

    public function setImageReference(string $image_reference): static
    {
        $this->image_reference = $image_reference;

        return $this;
    }

    public function getRelatedContent(): ?string
    {
        return $this->related_content;
    }

    public function setRelatedContent(string $related_content): static
    {
        $this->related_content = $related_content;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): static
    {
        $this->views = $views;

        return $this;
    }

    public function getIsRedesignVersion(): ?int
    {
        return $this->is_redesign_version;
    }

    public function setIsRedesignVersion(int $is_redesign_version): static
    {
        $this->is_redesign_version = $is_redesign_version;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(?string $intro): static
    {
        $this->intro = $intro;

        return $this;
    }

    public function getOptionalTag(): ?string
    {
        return $this->optional_tag;
    }

    public function setOptionalTag(?string $optional_tag): static
    {
        $this->optional_tag = $optional_tag;

        return $this;
    }

    public function getImgMain(): ?string
    {
        return $this->img_main;
    }

    public function setImgMain(string $img_main): static
    {
        $this->img_main = $img_main;

        return $this;
    }

    public function getSlider(): ?string
    {
        return $this->slider;
    }

    public function setSlider(?string $slider): static
    {
        $this->slider = $slider;

        return $this;
    }

    public function getPublic(): ?int
    {
        return $this->public;
    }

    public function setPublic(int $public): static
    {
        $this->public = $public;

        return $this;
    }

    public function getAdded(): ?string
    {
        return $this->added;
    }

    public function setAdded(string $added): static
    {
        $this->added = $added;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Service\ArticlesService;
use App\Service\BoxService;
use App\Service\CommentsService;
use App\Service\EventsService;
use App\Service\GalleryService;
use App\Service\IntroService;
use App\Service\NewsService;
use App\Service\SpotifyService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends BaseController
{
    private $introService;
    private $newsService;
    private $boxService;
    private $eventsService;
    private $galleryService;

    public function __construct(
        IntroService $introService,
        NewsService $newsService,
        BoxService $boxService, 
        EventsService $eventsService,
        GalleryService $galleryService,
    ) {
        $this->introService = $introService;
        $this->newsService = $newsService;
        $this->boxService = $boxService;
        $this->eventsService = $eventsService;
        $this->galleryService = $galleryService;
    }

    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        $intro = $this->introService->getIntroData();
        $news = $this->newsService->getNewsData();
        $box = $this->boxService->getBoxdata();
        $events = $this->eventsService->getEventsData();
        $gallery = $this->galleryService->getGalleryData();
        
        $response = $this->render('home/index.html.twig', [
            'introBlock1' => $intro[0],
            'introBlock2' => $intro[1],
            'introBlock3' => $intro[2],
            'news' => $news,
            'box' => $box,
            'events' => $events,
            'gallery' => $gallery,
        ]);

        $response->headers->set('Cache-Control', 'no-cache, no-store, must-revalidate');
        $response->headers->set('Pragma', 'no-cache');
        $response->headers->set('Expires', '0');
        
        return $response;
    }

    #[Route('spotify-playlist/{id}', name: 'app_spotify')]
    public function spotify(SpotifyService $spotifyService, string $id): Response
    {
        $template = $spotifyService->getPlaylist($id);
        return $this->render($template);
    }

    #[Route('comments/{id}', name: 'app_comments')]
    public function comments(CommentsService $commentsService, string $id): Response
    {       
        $comments = $commentsService->getResult($id);
        return $this->render('home/comments/comments-result.html.twig', [
            'comments' => $comments,
        ]);
    }

    #[Route('articles-result/{id}', name: 'app_articles')]
    public function articles(ArticlesService $articlesService, string $id): Response
    {
        $articles = $articlesService->getArticlesData($id);
        
        return $this->render('home/articles/articles-result.html.twig', [
            'articles' => $articles,
        ]);
    }
}

templates/home/banner.html.twig
<div class="c-banner">
	<div class="c-banner__item">
        <img src="{{ asset('images/banner--1.png') }}" width='728' height='90'>
    </div>
	<div class="c-banner__item">
		<img src="{{ asset('images/banner--2.png') }}" width='504' height='60'>
	</div>
</div>

templates/home/box.html.twig
<div class="u-mob-hide">
	<a href='{{ box.link }}' class='c-box-v2 c-box-v2--cube' style='background-image:url({{ box.image }}), url(images/default.png)'>
		<div class='c-box-v2__content'>
			<div><span class='c-tag'>Promo</span></div>	
			<div class='c-box-v2__date'>{{ box.date }}</div>		
			<h3 class='c-box-v2__title'>{{ box.title }}</h3>
			<div class='c-box-v2__footer'>{{ box.subtitle }}</div>
			<span class='c-arrow c-arrow--colored'></span>
		</div>
	</a>	
</div>

templates/home/gallery.html.twig
{% for galleryItem in gallery %}
    <a href='{{ galleryItem.urlPath }}' class='c-box-v5' style='background-image:url({{ galleryItem.image_reference }}), url(images/default.png)'>
        <div class='c-box-v5__content'>						
            <h3 class='c-box-v5__title'>
                {{ galleryItem.title }}
            </h3>
            <div class='c-item-footer'>
                <span class='c-item-footer__author'>{{ galleryItem.authorName }}</span> - <span class='c-item-footer__date'>{{ galleryItem.publish_date|date('d.m.Y') }}</span>
                <span class='c-box-v5__tag'>Počet fotek: {{ galleryItem.photosCount }}</span> <span class='c-box-v2__comments-count'>{{ galleryItem.comments_count }}</span>
            </div>
            <span class='c-arrow c-arrow--colored'></span>
        </div>
    </a>
{% endfor %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marast{% endblock %}
{% block pagename %}homepage{% endblock %}

{% block body %}

<div class="o-wrapper o-wrapper--main">
	<div class="o-container-outer o-container-outer--wide">
		<div class="o-container-flex">			
			{% include 'home/intro.html.twig' %}
		</div>

		{% include 'home/banner.html.twig' %}

		<div class="c-title c-title--compact">Novinky</div>	

		<div class="o-container-flex o-container-flex--tablet-reset">	
			{% include 'home/news.html.twig' %}	
			{% include 'home/box.html.twig' %}	
			{% include 'home/comments/comments.html.twig' %}	
		</div>			
	</div>
</div>

<section class="o-section u-bg-dark">
    <div class="o-container-outer o-container-outer--wide">
        {% include 'home/articles/articles.html.twig' %}
    </div>
</section>

<section class="o-section">
		<div class="o-container-outer o-container-outer--wide">			
			<div class="u-pb">
				<div class="c-detail-title c-detail-title--small">Galerie</div>
			</div>
			<div class="o-container-flex">
				{% include 'home/gallery.html.twig' %}
			</div>
			{% include 'home/banner.html.twig' %}
		</div>
	</section>

<section class="o-section u-bg-dark">
		<div class="o-container-outer o-container-outer--wide">
			{% include 'home/events/events.html.twig' %}
		</div>
	</section>
{% include 'home/spotify/spotify.html.twig' %}
{% endblock %}

templates/home/intro.html.twig
<a href='{{ introBlock1.urlPath }}' class='c-box-v3' style='background-image:url({{ introBlock1.image }}), url(images/default.png)'>	
    <div class='c-box-v3__content'>
        <div>
            <span class='c-tag'>{{ introBlock1.type }}</span>
        </div>							
        <h2 class='c-box-v3__title'>{{ introBlock1.title }}</h2>
        <span class='c-arrow'></span>
    </div>
    <div class='c-item-footer'>
        {{ introBlock1.authorName }} - <span class='c-item-footer__date'>{{ introBlock1.publishDate|date('d/m/Y') }}</span> <span class='c-item-footer__comments-count'> {{ introBlock1.commentsCount }}</span>
    </div>
</a>
<div>
    <a href='{{ introBlock2.urlPath }}' class='c-box-v4' style='background-image:url({{ introBlock2.image }}), url(images/default.png)'>	
        <div class='c-box-v4__content'>
            <div>
                <span class='c-tag'>{{ introBlock2.type }}</span>
            </div>							
            <h2 class='c-box-v4__title'>{{ introBlock2.title }}</h2>
            <span class='c-arrow'></span>
        </div>
        <div class='c-item-footer'>
        {{ introBlock2.authorName }} - <span class='c-item-footer__date'>{{ introBlock2.publishDate|date('d/m/Y') }}</span> <span class='c-item-footer__comments-count'> {{ introBlock2.commentsCount }}</span>
        </div>
    </a>
    <a href='{{ introBlock3.urlPath }}' class='c-box-v4' style='background-image:url({{ introBlock3.image }}), url(images/default.png)'>
        <div class='c-box-v4__content'>
            <div>
                <span class='c-tag'>{{ introBlock3.type }}</span>
            </div>	
            <h3 class='c-box-v4__title'>{{ introBlock3.title }}</h3>
            <span class='c-arrow'></span>
        </div>
        <div class='c-item-footer'>
        {{ introBlock3.authorName }} - <span class='c-item-footer__date'>{{ introBlock3.publishDate|date('d/m/Y') }}</span> <span class='c-item-footer__comments-count'> {{ introBlock3.commentsCount }}</span>
        </div>							
    </a>
</div>

templates/home/news.html.twig
<div>
	{% for item in news %}
		<a href='{{ path('app_novinky', {'url': item.urlPath}) }}' class='c-item-v1'>
                <div class='c-item-v1__img' style='background-image: url({{ item.image }}), url(images/default.png)'></div>
                <div class='c-item-v1__container c-item-v1__container--small'>                    
                    <div class='c-item-v1__tags'>
                        <span class='c-tag'>{{ item.type }}</span>{% if item.optionalTag is not empty %}<span class='c-tag'>{{ item.optionalTag }}</span>{% endif %}                        
                    </div>                    
                    <div class='c-item-v1__text'>{{ item.title }}</div>
                    <div class='c-item-v1__footer'>
                        <span class='c-item-v1__author'>{{ item.authorName }}</span> - <span class='c-item-v1__date'>{{ item.publishDate|date('d/m/y') }}</span> <span class='c-item-footer__comments-count c-item-footer__comments-count--dark'>{{ item.commentsCount }}</span>
                    </div>						
                </div>
            </a>	
	{% endfor %}
</div>